version: '3'
services:
  web:
    build: .
    environment:
      FLASK_APP: "app.py"
      FLASK_RUN_HOST: "0.0.0.0"
    volumes:
      - ./:/usr/src/app
    ports:
      - 3141:5000
  redis:
    image: "redis:alpine"
